name: Build live items.json

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser python-dateutil

      - name: Run harvester
        run: python fetch_feeds.py

      - name: Commit and push if items.json changed
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add items.json
            git commit -m "Update items.json"
            git push
          else
            echo "No changes to commit"
          fi
